export const DemoList = [
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description: 'An apple mobile which is nothing like apple',
    discountPercentage: 12.96,
    id: 1,
    price: 549,
    rating: 4.69,
    stock: 94,
    thumbnail: 'https://dummyjson.com/image/i/products/1/thumbnail.jpg',
    title: 'iPhone 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    discountPercentage: 17.94,
    id: 2,
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: 'https://dummyjson.com/image/i/products/2/thumbnail.jpg',
    title: 'iPhone X',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Samsung',
    category: 'smartphones',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    discountPercentage: 15.46,
    id: 3,
    price: 1249,
    rating: 4.09,
    stock: 36,
    thumbnail: 'https://dummyjson.com/image/i/products/3/thumbnail.jpg',
    title: 'Samsung Universe 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'OPPO',
    category: 'smartphones',
    description: 'OPPO F19 is officially announced on April 2021.',
    discountPercentage: 17.91,
    id: 4,
    price: 280,
    rating: 4.3,
    stock: 123,
    thumbnail: 'https://dummyjson.com/image/i/products/4/thumbnail.jpg',
    title: 'OPPOF19',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Huawei',
    category: 'smartphones',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    discountPercentage: 10.58,
    id: 5,
    price: 499,
    rating: 4.09,
    stock: 32,
    thumbnail: 'https://dummyjson.com/image/i/products/5/thumbnail.jpg',
    title: 'Huawei P30',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description: 'An apple mobile which is nothing like apple',
    discountPercentage: 12.96,
    id: 6,
    price: 549,
    rating: 4.69,
    stock: 94,
    thumbnail: 'https://dummyjson.com/image/i/products/1/thumbnail.jpg',
    title: 'iPhone 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    discountPercentage: 17.94,
    id: 7,
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: 'https://dummyjson.com/image/i/products/2/thumbnail.jpg',
    title: 'iPhone X',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Samsung',
    category: 'smartphones',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    discountPercentage: 15.46,
    id: 8,
    price: 1249,
    rating: 4.09,
    stock: 36,
    thumbnail: 'https://dummyjson.com/image/i/products/3/thumbnail.jpg',
    title: 'Samsung Universe 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'OPPO',
    category: 'smartphones',
    description: 'OPPO F19 is officially announced on April 2021.',
    discountPercentage: 17.91,
    id: 9,
    price: 280,
    rating: 4.3,
    stock: 123,
    thumbnail: 'https://dummyjson.com/image/i/products/4/thumbnail.jpg',
    title: 'OPPOF19',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Huawei',
    category: 'smartphones',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    discountPercentage: 10.58,
    id: 10,
    price: 499,
    rating: 4.09,
    stock: 32,
    thumbnail: 'https://dummyjson.com/image/i/products/5/thumbnail.jpg',
    title: 'Huawei P30',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description: 'An apple mobile which is nothing like apple',
    discountPercentage: 12.96,
    id: 11,
    price: 549,
    rating: 4.69,
    stock: 94,
    thumbnail: 'https://dummyjson.com/image/i/products/1/thumbnail.jpg',
    title: 'iPhone 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    discountPercentage: 17.94,
    id: 12,
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: 'https://dummyjson.com/image/i/products/2/thumbnail.jpg',
    title: 'iPhone X',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Samsung',
    category: 'smartphones',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    discountPercentage: 15.46,
    id: 13,
    price: 1249,
    rating: 4.09,
    stock: 36,
    thumbnail: 'https://dummyjson.com/image/i/products/3/thumbnail.jpg',
    title: 'Samsung Universe 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'OPPO',
    category: 'smartphones',
    description: 'OPPO F19 is officially announced on April 2021.',
    discountPercentage: 17.91,
    id: 14,
    price: 280,
    rating: 4.3,
    stock: 123,
    thumbnail: 'https://dummyjson.com/image/i/products/4/thumbnail.jpg',
    title: 'OPPOF19',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Huawei',
    category: 'smartphones',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    discountPercentage: 10.58,
    id: 15,
    price: 499,
    rating: 4.09,
    stock: 32,
    thumbnail: 'https://dummyjson.com/image/i/products/5/thumbnail.jpg',
    title: 'Huawei P30',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description: 'An apple mobile which is nothing like apple',
    discountPercentage: 12.96,
    id: 16,
    price: 549,
    rating: 4.69,
    stock: 94,
    thumbnail: 'https://dummyjson.com/image/i/products/1/thumbnail.jpg',
    title: 'iPhone 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    discountPercentage: 17.94,
    id: 17,
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: 'https://dummyjson.com/image/i/products/2/thumbnail.jpg',
    title: 'iPhone X',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Samsung',
    category: 'smartphones',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    discountPercentage: 15.46,
    id: 18,
    price: 1249,
    rating: 4.09,
    stock: 36,
    thumbnail: 'https://dummyjson.com/image/i/products/3/thumbnail.jpg',
    title: 'Samsung Universe 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'OPPO',
    category: 'smartphones',
    description: 'OPPO F19 is officially announced on April 2021.',
    discountPercentage: 17.91,
    id: 19,
    price: 280,
    rating: 4.3,
    stock: 123,
    thumbnail: 'https://dummyjson.com/image/i/products/4/thumbnail.jpg',
    title: 'OPPOF19',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Huawei',
    category: 'smartphones',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    discountPercentage: 10.58,
    id: 20,
    price: 499,
    rating: 4.09,
    stock: 32,
    thumbnail: 'https://dummyjson.com/image/i/products/5/thumbnail.jpg',
    title: 'Huawei P30',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description: 'An apple mobile which is nothing like apple',
    discountPercentage: 12.96,
    id: 21,
    price: 549,
    rating: 4.69,
    stock: 94,
    thumbnail: 'https://dummyjson.com/image/i/products/1/thumbnail.jpg',
    title: 'iPhone 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    discountPercentage: 17.94,
    id: 22,
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: 'https://dummyjson.com/image/i/products/2/thumbnail.jpg',
    title: 'iPhone X',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Samsung',
    category: 'smartphones',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    discountPercentage: 15.46,
    id: 23,
    price: 1249,
    rating: 4.09,
    stock: 36,
    thumbnail: 'https://dummyjson.com/image/i/products/3/thumbnail.jpg',
    title: 'Samsung Universe 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'OPPO',
    category: 'smartphones',
    description: 'OPPO F19 is officially announced on April 2021.',
    discountPercentage: 17.91,
    id: 24,
    price: 280,
    rating: 4.3,
    stock: 123,
    thumbnail: 'https://dummyjson.com/image/i/products/4/thumbnail.jpg',
    title: 'OPPOF19',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Huawei',
    category: 'smartphones',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    discountPercentage: 10.58,
    id: 25,
    price: 499,
    rating: 4.09,
    stock: 32,
    thumbnail: 'https://dummyjson.com/image/i/products/5/thumbnail.jpg',
    title: 'Huawei P30',
  },
];
