export const DataList = [
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description: 'An apple mobile which is nothing like apple',
    discountPercentage: 12.96,
    id: 1,
    price: 549,
    rating: 4.69,
    stock: 94,
    thumbnail: 'https://dummyjson.com/image/i/products/1/thumbnail.jpg',
    title: 'iPhone 9',
  },
  {
    cart: false,
    quentity: 0,
    brand: 'Apple',
    category: 'smartphones',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    discountPercentage: 17.94,
    id: 2,
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: 'https://dummyjson.com/image/i/products/2/thumbnail.jpg',
    title: 'iPhone X',
  },
];
